hwdec=auto
vo=gpu-next
gpu-api=auto
scale=ewa_lanczossharp
dscale=catmull_rom
cscale=bilinear
sub-font-size=48
sub-color="#FFFFFFFF"
sub-border-color="#FF000000"
sub-border-size=2
vd-lavc-threads=4
demuxer-thread=yes
hdr-compute-peak=yes
tone-mapping=auto
audio-samplerate=48000
ao=pipewire
osc=no

# Keeps the GUI window open for audio-only files
force-window=yes

# Optional: Prevents mpv from closing after the last audio file finishes
keep-open=yes

