# Imports

# Default stuff
background_opacity          0.6
cursor_trail                1
window_padding_width 0 0 0 15
clear_all_shortcuts no
copy_on_select      yes
confirm_os_window_close 0

# Custom Keymaps
map alt+n           no_op

map alt+Up          neighboring_window up
map alt+Down        neighboring_window down
map alt+Left        neighboring_window left
map alt+Right       neighboring_window right

map alt+.           next_tab
map alt+,           previous_tab

# Optimizations
repaint_delay       16
input_delay         2
sync_to_monitor     yes

# Looks and Interface
font_size           11.0

# Tab bar styling
tab_bar_style       powerline
tab_powerline_style slanted
active_tab_font_style bold
include themes/noctalia.conf
