# Tab 1: System Info & Shell
new_tab Terminal
launch sh -c "fastfetch; exec $SHELL"

# Tab 2: Monitoring & Music (Vertical Split)
new_tab System and Media
layout splits
launch btop
launch --location=hsplit rmpc
