color0 #17293b
color1 #fd4663
color2 #67bbe4
color3 #657ee2
color4 #9372d9
color5 #93cfec
color6 #96a5e9
color7 #f2f2f3
color8 #5f6a6f
color9 #fd4663
color10 #67bbe4
color11 #657ee2
color12 #9372d9
color13 #93cfec
color14 #96a5e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #111e2c
background            #111e2c
foreground            #f2f2f3
selection_foreground  #afb4b6
selection_background  #17293b
active_border_color   #67bbe4
inactive_border_color #17293b
url_color             #67bbe4

active_tab_foreground   #182125
active_tab_background   #67bbe4
inactive_tab_foreground #afb4b6
inactive_tab_background #17293b
cursor_trail_color      #afb4b6
